name: config-request-automation
on:
  issues:
    types: [opened, edited]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  label-and-assign-project:
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v1.1.0
        with:
          issue_id: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          separator: '###'
          label_marker_start: ' '
          label_marker_end: ' '
      - name: Label Brand
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: ${{ fromJSON(steps.parse.outputs.payload)[' Brand'] }}
      - name: Label Productline
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: ${{ fromJSON(steps.parse.outputs.payload)[' Productline'] }}
      - name: Move Card to In Progress
        uses: peter-evans/create-or-update-project-card@v1
        if: contains(github.event.issue.labels.*.name, 'Configuration-Request')
        with:
          project-name: 'ONE.Shop Configuration Requests'
          column-name: 'To do'
          issue-number: ${{ github.event.issue.number }}
  automated-pr-from-issue:
    needs: label-and-assign-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v1.1.0
        with:
          issue_id: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          separator: '###'
          label_marker_start: ' '
          label_marker_end: ' '
      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"
      - name: Uncommitted change for testing
        run: date +%s > test-automated-config-update.txt
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'feat: update config for issue #${{ github.event.issue.number }}'
          committer: ONE.Shop Config Bot <thomas.haug@diconium.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: feature/auto-generated-config-update-${{ github.event.issue.number }}
          delete-branch: true
          title: '[Config-Request] update config for issue #${{ github.event.issue.number }}'
          body: 'Closes #${{ github.event.issue.number }}'
          draft: false
      - name: Move Issue Card to In Progress
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: 'ONE.Shop Configuration Requests'
          column-name: 'In progress'
          issue-number: ${{ github.event.issue.number }}
      - name: Move PR Card to In Progress
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: 'ONE.Shop Configuration Requests'
          column-name: 'In progress'
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
